### PR TITLE
fixed bracket spacing

### PR DESCRIPTION
**Pull request by UVLabs**

### CODE REVIEW

**Comment by pmgllc** [comment]
-- Please reply above this line --

Hello, {%customer.firstName,fallback=emailing person},

I got your email. 

I'll be taking the rest of the year off to be with family. I'll check
in from time to time to make sure the world isn't burning. I may or
may not respond to non-burning items, depending on the day and moment
I check. If you get this message in response to a question and decide
things aren't on fire, please reply and I'll flag for January.

Thanks for reading this auto-reply.

-----------------------------------------------------------
## Mathetos/demo-Delayed-Admin-Notice-Plugi sent a message, on Dec 16 @ 11:55pm (EST):


-------------------------

You Can View, Comment On, Or Merge This Pull Request Online At:

	 https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4
[1] 

Commit Summary

	* fixed bracket spacing

File Changes

	* M plugin.php [2] (4)

Patch Links:

	*
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4.patch
[3]
 	*
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4.diff
[4]

	-
 You are receiving this because you are subscribed to this thread.
 Reply to this email directly, view it on GitHub [5], or mute the
thread [6].

Links:
------
[1]
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4
[2]
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4/files#diff-0
[3]
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4.patch
[4]
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4.diff
[5]
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4
[6]

**Comment by mathetos** [comment]
Good catch! Thanks again!

**Comment by pmgllc** [comment]
-- Please reply above this line --

Hello, {%customer.firstName,fallback=emailing person},

I got your email. 

I'll be taking the rest of the year off to be with family. I'll check
in from time to time to make sure the world isn't burning. I may or
may not respond to non-burning items, depending on the day and moment
I check. If you get this message in response to a question and decide
things aren't on fire, please reply and I'll flag for January.

Thanks for reading this auto-reply.

-----------------------------------------------------------
## Mathetos/demo-Delayed-Admin-Notice-Plugi sent a message, on Dec 17 @ 1:24pm (EST):



	Good catch! Thanks again! 

	-
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub [1], or mute the
thread [2].

Links:
------
[1]
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4#issuecomment-267778437
[2]

**Comment by pmgllc** [comment]
-- Please reply above this line --

Hello, {%customer.firstName,fallback=emailing person},

I got your email. 

I'll be taking the rest of the year off to be with family. I'll check
in from time to time to make sure the world isn't burning. I may or
may not respond to non-burning items, depending on the day and moment
I check. If you get this message in response to a question and decide
things aren't on fire, please reply and I'll flag for January.

Thanks for reading this auto-reply.

-----------------------------------------------------------
## Mathetos/demo-Delayed-Admin-Notice-Plugi sent a message, on Dec 17 @ 1:24pm (EST):



	Merged #4 [1]. 

	-
 You are receiving this because you commented.
 Reply to this email directly, view it on GitHub [2], or mute the
thread [3].

Links:
------
[1]
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4
[2]
https://github.com/mathetos/demo-delayed-admin-notice-plugin/pull/4#event-897660903
[3]

**Pull request merged**
